# Site settings
title: IdentityServer3
email: identity@leastprivilege.com
description: IdentityServer
baseurl: "/Documentation" # the subpath of your site, e.g. /blog/
url: "https://identityserver.github.io" # the base hostname & protocol for your site
twitter_username: identityserver
github_username: identityserver

# Build settings
markdown: redcarpet
highlighter: pygments

# Custom Settings
github_url: https://github.com/IdentityServer/Documentation
site_github_url: https://github.com/IdentityServer/Documentation
edit_on_github_url: https://github.com/IdentityServer/Documentation/edit/gh-pages/%path%
