# Site settings
title: IdentityServer
email: identity@thinktecture.com
description: IdentityServer Documentation
baseurl: "/Thinktecture.IdentityServer.v3.Documentation" # the subpath of your site, e.g. /blog/
url: "https://thinktecture.github.io" # the base hostname & protocol for your site
twitter_username: identityserver
github_username:  thinktecture

# Build settings
markdown: redcarpet
highlighter: pygments

# Custom Settings
github_url: https://github.com/thinktecture/Thinktecture.IdentityServer.v3.Documentation
site_github_url: https://github.com/thinktecture/Thinktecture.IdentityServer.v3.Documentation
edit_on_github_url: https://github.com/thinktecture/Thinktecture.IdentityServer.v3.Documentation/gh-pages/%path%